### ISSUE TITLE
Live demo seems to be broken

### ISSUE THREAD

**Issue by r0ckarong** [TimeBandit/graphSub#8]
I wanted to check this out but the live demo gives me a few 404 errors and won't work.

![screen shot 2016-04-29 at 17 48 17](https://cloud.githubusercontent.com/assets/4920542/14921467/abfba576-0e32-11e6-8a3c-22e89ef5e7f3.png)

**Comment by TimeBandit** [comment]
Hi, that's a bummer, well it's not anything that I have done. If you download the repo and open `index.html` you'll see the working demo. I'll update the site, Thank :+1:
